<?php declare(strict_types=1);
namespace Tiny\Tags\HTML;

use Tiny\Core\HTML;

function a(): HTML          {return call_user_func_array('\Tiny\Core\HTML::a', func_get_args());}
function abbr(): HTML       {return call_user_func_array('\Tiny\Core\HTML::abbr', func_get_args());}
function address(): HTML    {return call_user_func_array('\Tiny\Core\HTML::address', func_get_args());}
function area(): HTML       {return call_user_func_array('\Tiny\Core\HTML::area', func_get_args());}
function article(): HTML    {return call_user_func_array('\Tiny\Core\HTML::article', func_get_args());}
function aside(): HTML      {return call_user_func_array('\Tiny\Core\HTML::aside', func_get_args());}
function audio(): HTML      {return call_user_func_array('\Tiny\Core\HTML::audio', func_get_args());}
function b(): HTML          {return call_user_func_array('\Tiny\Core\HTML::b', func_get_args());}
function base(): HTML       {return call_user_func_array('\Tiny\Core\HTML::base', func_get_args());}
function bdi(): HTML        {return call_user_func_array('\Tiny\Core\HTML::bdi', func_get_args());}
function bdo(): HTML        {return call_user_func_array('\Tiny\Core\HTML::bdo', func_get_args());}
function blockquote(): HTML {return call_user_func_array('\Tiny\Core\HTML::blockquote', func_get_args());}
function body(): HTML       {return call_user_func_array('\Tiny\Core\HTML::body', func_get_args());}
function br(): HTML         {return call_user_func_array('\Tiny\Core\HTML::br', func_get_args());}
function button(): HTML     {return call_user_func_array('\Tiny\Core\HTML::button', func_get_args());}
function canvas(): HTML     {return call_user_func_array('\Tiny\Core\HTML::canvas', func_get_args());}
function caption(): HTML    {return call_user_func_array('\Tiny\Core\HTML::caption', func_get_args());}
function cite(): HTML       {return call_user_func_array('\Tiny\Core\HTML::cite', func_get_args());}
function code(): HTML       {return call_user_func_array('\Tiny\Core\HTML::code', func_get_args());}
function col(): HTML        {return call_user_func_array('\Tiny\Core\HTML::col', func_get_args());}
function colgroup(): HTML   {return call_user_func_array('\Tiny\Core\HTML::colgroup', func_get_args());}
function data(): HTML       {return call_user_func_array('\Tiny\Core\HTML::data', func_get_args());}
function datalist(): HTML   {return call_user_func_array('\Tiny\Core\HTML::datalist', func_get_args());}
function dd(): HTML         {return call_user_func_array('\Tiny\Core\HTML::dd', func_get_args());}
function del(): HTML        {return call_user_func_array('\Tiny\Core\HTML::del', func_get_args());}
function details(): HTML    {return call_user_func_array('\Tiny\Core\HTML::details', func_get_args());}
function dfn(): HTML        {return call_user_func_array('\Tiny\Core\HTML::dfn', func_get_args());}
function dialog(): HTML     {return call_user_func_array('\Tiny\Core\HTML::dialog', func_get_args());}
function div(): HTML        {return call_user_func_array('\Tiny\Core\HTML::div', func_get_args());}
function dl(): HTML         {return call_user_func_array('\Tiny\Core\HTML::dl', func_get_args());}
function dt(): HTML         {return call_user_func_array('\Tiny\Core\HTML::dt', func_get_args());}
function em(): HTML         {return call_user_func_array('\Tiny\Core\HTML::em', func_get_args());}
function embed(): HTML      {return call_user_func_array('\Tiny\Core\HTML::embed', func_get_args());}
function fieldset(): HTML   {return call_user_func_array('\Tiny\Core\HTML::fieldset', func_get_args());}
function figcaption(): HTML {return call_user_func_array('\Tiny\Core\HTML::figcaption', func_get_args());}
function figure(): HTML     {return call_user_func_array('\Tiny\Core\HTML::figure', func_get_args());}
function footer(): HTML     {return call_user_func_array('\Tiny\Core\HTML::footer', func_get_args());}
function form(): HTML       {return call_user_func_array('\Tiny\Core\HTML::form', func_get_args());}
function h1(): HTML         {return call_user_func_array('\Tiny\Core\HTML::h1', func_get_args());}
function h2(): HTML         {return call_user_func_array('\Tiny\Core\HTML::h2', func_get_args());}
function h3(): HTML         {return call_user_func_array('\Tiny\Core\HTML::h3', func_get_args());}
function h4(): HTML         {return call_user_func_array('\Tiny\Core\HTML::h4', func_get_args());}
function h5(): HTML         {return call_user_func_array('\Tiny\Core\HTML::h5', func_get_args());}
function h6(): HTML         {return call_user_func_array('\Tiny\Core\HTML::h6', func_get_args());}
function head(): HTML       {return call_user_func_array('\Tiny\Core\HTML::head', func_get_args());}
function header(): HTML     {return call_user_func_array('\Tiny\Core\HTML::header', func_get_args());}
function hgroup(): HTML     {return call_user_func_array('\Tiny\Core\HTML::hgroup', func_get_args());}
function hr(): HTML         {return call_user_func_array('\Tiny\Core\HTML::hr', func_get_args());}
function html(): HTML       {return call_user_func_array('\Tiny\Core\HTML::html', func_get_args());}
function i(): HTML          {return call_user_func_array('\Tiny\Core\HTML::i', func_get_args());}
function iframe(): HTML     {return call_user_func_array('\Tiny\Core\HTML::iframe', func_get_args());}
function img(): HTML        {return call_user_func_array('\Tiny\Core\HTML::img', func_get_args());}
function input(): HTML      {return call_user_func_array('\Tiny\Core\HTML::input', func_get_args());}
function ins(): HTML        {return call_user_func_array('\Tiny\Core\HTML::ins', func_get_args());}
function kbd(): HTML        {return call_user_func_array('\Tiny\Core\HTML::kbd', func_get_args());}
function label(): HTML      {return call_user_func_array('\Tiny\Core\HTML::label', func_get_args());}
function legend(): HTML     {return call_user_func_array('\Tiny\Core\HTML::legend', func_get_args());}
function li(): HTML         {return call_user_func_array('\Tiny\Core\HTML::li', func_get_args());}
function link(): HTML       {return call_user_func_array('\Tiny\Core\HTML::link', func_get_args());}
function main(): HTML       {return call_user_func_array('\Tiny\Core\HTML::main', func_get_args());}
function map(): HTML        {return call_user_func_array('\Tiny\Core\HTML::map', func_get_args());}
function mark(): HTML       {return call_user_func_array('\Tiny\Core\HTML::mark', func_get_args());}
function menu(): HTML       {return call_user_func_array('\Tiny\Core\HTML::menu', func_get_args());}
function meta(): HTML       {return call_user_func_array('\Tiny\Core\HTML::meta', func_get_args());}
function meter(): HTML      {return call_user_func_array('\Tiny\Core\HTML::meter', func_get_args());}
function nav(): HTML        {return call_user_func_array('\Tiny\Core\HTML::nav', func_get_args());}
function noscript(): HTML   {return call_user_func_array('\Tiny\Core\HTML::noscript', func_get_args());}
function object(): HTML     {return call_user_func_array('\Tiny\Core\HTML::object', func_get_args());}
function ol(): HTML         {return call_user_func_array('\Tiny\Core\HTML::ol', func_get_args());}
function optgroup(): HTML   {return call_user_func_array('\Tiny\Core\HTML::optgroup', func_get_args());}
function option(): HTML     {return call_user_func_array('\Tiny\Core\HTML::option', func_get_args());}
function output(): HTML     {return call_user_func_array('\Tiny\Core\HTML::output', func_get_args());}
function p(): HTML          {return call_user_func_array('\Tiny\Core\HTML::p', func_get_args());}
function picture(): HTML    {return call_user_func_array('\Tiny\Core\HTML::picture', func_get_args());}
function pre(): HTML        {return call_user_func_array('\Tiny\Core\HTML::pre', func_get_args());}
function progress(): HTML   {return call_user_func_array('\Tiny\Core\HTML::progress', func_get_args());}
function q(): HTML          {return call_user_func_array('\Tiny\Core\HTML::q', func_get_args());}
function rp(): HTML         {return call_user_func_array('\Tiny\Core\HTML::rp', func_get_args());}
function rt(): HTML         {return call_user_func_array('\Tiny\Core\HTML::rt', func_get_args());}
function ruby(): HTML       {return call_user_func_array('\Tiny\Core\HTML::ruby', func_get_args());}
function s(): HTML          {return call_user_func_array('\Tiny\Core\HTML::s', func_get_args());}
function samp(): HTML       {return call_user_func_array('\Tiny\Core\HTML::samp', func_get_args());}
function script(): HTML     {return call_user_func_array('\Tiny\Core\HTML::script', func_get_args());}
function section(): HTML    {return call_user_func_array('\Tiny\Core\HTML::section', func_get_args());}
function select(): HTML     {return call_user_func_array('\Tiny\Core\HTML::select', func_get_args());}
function slot(): HTML       {return call_user_func_array('\Tiny\Core\HTML::slot', func_get_args());}
function small(): HTML      {return call_user_func_array('\Tiny\Core\HTML::small', func_get_args());}
function source(): HTML     {return call_user_func_array('\Tiny\Core\HTML::source', func_get_args());}
function span(): HTML       {return call_user_func_array('\Tiny\Core\HTML::span', func_get_args());}
function strong(): HTML     {return call_user_func_array('\Tiny\Core\HTML::strong', func_get_args());}
function style(): HTML      {return call_user_func_array('\Tiny\Core\HTML::style', func_get_args());}
function sub(): HTML        {return call_user_func_array('\Tiny\Core\HTML::sub', func_get_args());}
function summary(): HTML    {return call_user_func_array('\Tiny\Core\HTML::summary', func_get_args());}
function sup(): HTML        {return call_user_func_array('\Tiny\Core\HTML::sup', func_get_args());}
function table(): HTML      {return call_user_func_array('\Tiny\Core\HTML::table', func_get_args());}
function tbody(): HTML      {return call_user_func_array('\Tiny\Core\HTML::tbody', func_get_args());}
function td(): HTML         {return call_user_func_array('\Tiny\Core\HTML::td', func_get_args());}
function template(): HTML   {return call_user_func_array('\Tiny\Core\HTML::template', func_get_args());}
function textarea(): HTML   {return call_user_func_array('\Tiny\Core\HTML::textarea', func_get_args());}
function tfoot(): HTML      {return call_user_func_array('\Tiny\Core\HTML::tfoot', func_get_args());}
function th(): HTML         {return call_user_func_array('\Tiny\Core\HTML::th', func_get_args());}
function thead(): HTML      {return call_user_func_array('\Tiny\Core\HTML::thead', func_get_args());}
function time(): HTML       {return call_user_func_array('\Tiny\Core\HTML::time', func_get_args());}
function title(): HTML      {return call_user_func_array('\Tiny\Core\HTML::title', func_get_args());}
function tr(): HTML         {return call_user_func_array('\Tiny\Core\HTML::tr', func_get_args());}
function track(): HTML      {return call_user_func_array('\Tiny\Core\HTML::track', func_get_args());}
function u(): HTML          {return call_user_func_array('\Tiny\Core\HTML::u', func_get_args());}
function ul(): HTML         {return call_user_func_array('\Tiny\Core\HTML::ul', func_get_args());}
function video(): HTML      {return call_user_func_array('\Tiny\Core\HTML::video', func_get_args());}
function wbr(): HTML        {return call_user_func_array('\Tiny\Core\HTML::wbr', func_get_args());}
