<?php declare(strict_types=1);
namespace Pure\SVG;

use Pure\Core\SVG;

function a(): SVG                      {return call_user_func_array('\Pure\Core\SVG::a', func_get_args());}
function animate(): SVG                {return call_user_func_array('\Pure\Core\SVG::animate', func_get_args());}
function animateMotion(): SVG          {return call_user_func_array('\Pure\Core\SVG::animateMotion', func_get_args());}
function animateTransform(): SVG       {return call_user_func_array('\Pure\Core\SVG::animateTransform', func_get_args());}
function circle(): SVG                 {return call_user_func_array('\Pure\Core\SVG::circle', func_get_args());}
function clipPath(): SVG               {return call_user_func_array('\Pure\Core\SVG::clipPath', func_get_args());}
function defs(): SVG                   {return call_user_func_array('\Pure\Core\SVG::defs', func_get_args());}
function desc(): SVG                   {return call_user_func_array('\Pure\Core\SVG::desc', func_get_args());}
function ellipse(): SVG                {return call_user_func_array('\Pure\Core\SVG::ellipse', func_get_args());}
function feBlend(): SVG                {return call_user_func_array('\Pure\Core\SVG::feBlend', func_get_args());}
function feColorMatrix(): SVG          {return call_user_func_array('\Pure\Core\SVG::feColorMatrix', func_get_args());}
function feComponentTransfer(): SVG    {return call_user_func_array('\Pure\Core\SVG::feComponentTransfer', func_get_args());}
function feComposite(): SVG            {return call_user_func_array('\Pure\Core\SVG::feComposite', func_get_args());}
function feConvolveMatrix(): SVG       {return call_user_func_array('\Pure\Core\SVG::feConvolveMatrix', func_get_args());}
function feDiffuseLighting(): SVG      {return call_user_func_array('\Pure\Core\SVG::feDiffuseLighting', func_get_args());}
function feDisplacementMap(): SVG      {return call_user_func_array('\Pure\Core\SVG::feDisplacementMap', func_get_args());}
function feDistantLight(): SVG         {return call_user_func_array('\Pure\Core\SVG::feDistantLight', func_get_args());}
function feDropShadow(): SVG           {return call_user_func_array('\Pure\Core\SVG::feDropShadow', func_get_args());}
function feFlood(): SVG                {return call_user_func_array('\Pure\Core\SVG::feFlood', func_get_args());}
function feFuncA(): SVG                {return call_user_func_array('\Pure\Core\SVG::feFuncA', func_get_args());}
function feFuncB(): SVG                {return call_user_func_array('\Pure\Core\SVG::feFuncB', func_get_args());}
function feFuncG(): SVG                {return call_user_func_array('\Pure\Core\SVG::feFuncG', func_get_args());}
function feFuncR(): SVG                {return call_user_func_array('\Pure\Core\SVG::feFuncR', func_get_args());}
function feGaussianBlur(): SVG         {return call_user_func_array('\Pure\Core\SVG::feGaussianBlur', func_get_args());}
function feImage(): SVG                {return call_user_func_array('\Pure\Core\SVG::feImage', func_get_args());}
function feMerge(): SVG                {return call_user_func_array('\Pure\Core\SVG::feMerge', func_get_args());}
function feMergeNode(): SVG            {return call_user_func_array('\Pure\Core\SVG::feMergeNode', func_get_args());}
function feMorphology(): SVG           {return call_user_func_array('\Pure\Core\SVG::feMorphology', func_get_args());}
function feOffset(): SVG               {return call_user_func_array('\Pure\Core\SVG::feOffset', func_get_args());}
function fePointLight(): SVG           {return call_user_func_array('\Pure\Core\SVG::fePointLight', func_get_args());}
function feSpecularLighting(): SVG     {return call_user_func_array('\Pure\Core\SVG::feSpecularLighting', func_get_args());}
function feSpotLight(): SVG            {return call_user_func_array('\Pure\Core\SVG::feSpotLight', func_get_args());}
function feTile(): SVG                 {return call_user_func_array('\Pure\Core\SVG::feTile', func_get_args());}
function feTurbulence(): SVG           {return call_user_func_array('\Pure\Core\SVG::feTurbulence', func_get_args());}
function filter(): SVG                 {return call_user_func_array('\Pure\Core\SVG::filter', func_get_args());}
function foreignObject(): SVG          {return call_user_func_array('\Pure\Core\SVG::foreignObject', func_get_args());}
function g(): SVG                      {return call_user_func_array('\Pure\Core\SVG::g', func_get_args());}
function image(): SVG                  {return call_user_func_array('\Pure\Core\SVG::image', func_get_args());}
function line(): SVG                   {return call_user_func_array('\Pure\Core\SVG::line', func_get_args());}
function linearGradient(): SVG         {return call_user_func_array('\Pure\Core\SVG::linearGradient', func_get_args());}
function marker(): SVG                 {return call_user_func_array('\Pure\Core\SVG::marker', func_get_args());}
function mask(): SVG                   {return call_user_func_array('\Pure\Core\SVG::mask', func_get_args());}
function metadata(): SVG               {return call_user_func_array('\Pure\Core\SVG::metadata', func_get_args());}
function mpath(): SVG                  {return call_user_func_array('\Pure\Core\SVG::mpath', func_get_args());}
function path(): SVG                   {return call_user_func_array('\Pure\Core\SVG::path', func_get_args());}
function pattern(): SVG                {return call_user_func_array('\Pure\Core\SVG::pattern', func_get_args());}
function polygon(): SVG                {return call_user_func_array('\Pure\Core\SVG::polygon', func_get_args());}
function polyline(): SVG               {return call_user_func_array('\Pure\Core\SVG::polyline', func_get_args());}
function radialGradient(): SVG         {return call_user_func_array('\Pure\Core\SVG::radialGradient', func_get_args());}
function rect(): SVG                   {return call_user_func_array('\Pure\Core\SVG::rect', func_get_args());}
function script(): SVG                 {return call_user_func_array('\Pure\Core\SVG::script', func_get_args());}
function set(): SVG                    {return call_user_func_array('\Pure\Core\SVG::set', func_get_args());}
function stop(): SVG                   {return call_user_func_array('\Pure\Core\SVG::stop', func_get_args());}
function style(): SVG                  {return call_user_func_array('\Pure\Core\SVG::style', func_get_args());}
function svg(): SVG                    {return call_user_func_array('\Pure\Core\SVG::svg', func_get_args());}
function svgSwitch(): SVG              {return call_user_func_array('\Pure\Core\SVG::switch', func_get_args());}
function symbol(): SVG                 {return call_user_func_array('\Pure\Core\SVG::symbol', func_get_args());}
function text(): SVG                   {return call_user_func_array('\Pure\Core\SVG::text', func_get_args());}
function textPath(): SVG               {return call_user_func_array('\Pure\Core\SVG::textPath', func_get_args());}
function title(): SVG                  {return call_user_func_array('\Pure\Core\SVG::title', func_get_args());}
function tspan(): SVG                  {return call_user_func_array('\Pure\Core\SVG::tspan', func_get_args());}
function svgUse(): SVG                 {return call_user_func_array('\Pure\Core\SVG::use', func_get_args());}
function view(): SVG                   {return call_user_func_array('\Pure\Core\SVG::view', func_get_args());}
