<?php
namespace Tiny;

require_once __DIR__ . '/Tag.php';

function a()          {return call_user_func_array('\Tiny\Tag::a', func_get_args());}
function abbr()       {return call_user_func_array('\Tiny\Tag::abbr', func_get_args());}
function address()    {return call_user_func_array('\Tiny\Tag::address', func_get_args());}
function area()       {return call_user_func_array('\Tiny\Tag::area', func_get_args());}
function article()    {return call_user_func_array('\Tiny\Tag::article', func_get_args());}
function aside()      {return call_user_func_array('\Tiny\Tag::aside', func_get_args());}
function audio()      {return call_user_func_array('\Tiny\Tag::audio', func_get_args());}
function b()          {return call_user_func_array('\Tiny\Tag::b', func_get_args());}
function base()       {return call_user_func_array('\Tiny\Tag::base', func_get_args());}
function bdi()        {return call_user_func_array('\Tiny\Tag::bdi', func_get_args());}
function bdo()        {return call_user_func_array('\Tiny\Tag::bdo', func_get_args());}
function blockquote() {return call_user_func_array('\Tiny\Tag::blockquote', func_get_args());}
function body()       {return call_user_func_array('\Tiny\Tag::body', func_get_args());}
function br()         {return call_user_func_array('\Tiny\Tag::br', func_get_args());}
function button()     {return call_user_func_array('\Tiny\Tag::button', func_get_args());}
function canvas()     {return call_user_func_array('\Tiny\Tag::canvas', func_get_args());}
function caption()    {return call_user_func_array('\Tiny\Tag::caption', func_get_args());}
function cite()       {return call_user_func_array('\Tiny\Tag::cite', func_get_args());}
function code()       {return call_user_func_array('\Tiny\Tag::code', func_get_args());}
function col()        {return call_user_func_array('\Tiny\Tag::col', func_get_args());}
function colgroup()   {return call_user_func_array('\Tiny\Tag::colgroup', func_get_args());}
function data()       {return call_user_func_array('\Tiny\Tag::data', func_get_args());}
function datalist()   {return call_user_func_array('\Tiny\Tag::datalist', func_get_args());}
function dd()         {return call_user_func_array('\Tiny\Tag::dd', func_get_args());}
function del()        {return call_user_func_array('\Tiny\Tag::del', func_get_args());}
function details()    {return call_user_func_array('\Tiny\Tag::details', func_get_args());}
function dfn()        {return call_user_func_array('\Tiny\Tag::dfn', func_get_args());}
function dialog()     {return call_user_func_array('\Tiny\Tag::dialog', func_get_args());}
function div()        {return call_user_func_array('\Tiny\Tag::div', func_get_args());}
function dl()         {return call_user_func_array('\Tiny\Tag::dl', func_get_args());}
function dt()         {return call_user_func_array('\Tiny\Tag::dt', func_get_args());}
function em()         {return call_user_func_array('\Tiny\Tag::em', func_get_args());}
function embed()      {return call_user_func_array('\Tiny\Tag::embed', func_get_args());}
function fieldset()   {return call_user_func_array('\Tiny\Tag::fieldset', func_get_args());}
function figcaption() {return call_user_func_array('\Tiny\Tag::figcaption', func_get_args());}
function figure()     {return call_user_func_array('\Tiny\Tag::figure', func_get_args());}
function footer()     {return call_user_func_array('\Tiny\Tag::footer', func_get_args());}
function form()       {return call_user_func_array('\Tiny\Tag::form', func_get_args());}
function h1()         {return call_user_func_array('\Tiny\Tag::h1', func_get_args());}
function h2()         {return call_user_func_array('\Tiny\Tag::h2', func_get_args());}
function h3()         {return call_user_func_array('\Tiny\Tag::h3', func_get_args());}
function h4()         {return call_user_func_array('\Tiny\Tag::h4', func_get_args());}
function h5()         {return call_user_func_array('\Tiny\Tag::h5', func_get_args());}
function h6()         {return call_user_func_array('\Tiny\Tag::h6', func_get_args());}
function head()       {return call_user_func_array('\Tiny\Tag::head', func_get_args());}
function header()     {return call_user_func_array('\Tiny\Tag::header', func_get_args());}
function hgroup()     {return call_user_func_array('\Tiny\Tag::hgroup', func_get_args());}
function hr()         {return call_user_func_array('\Tiny\Tag::hr', func_get_args());}
function html()       {return call_user_func_array('\Tiny\Tag::html', func_get_args());}
function i()          {return call_user_func_array('\Tiny\Tag::i', func_get_args());}
function iframe()     {return call_user_func_array('\Tiny\Tag::iframe', func_get_args());}
function img()        {return call_user_func_array('\Tiny\Tag::img', func_get_args());}
function input()      {return call_user_func_array('\Tiny\Tag::input', func_get_args());}
function ins()        {return call_user_func_array('\Tiny\Tag::ins', func_get_args());}
function kbd()        {return call_user_func_array('\Tiny\Tag::kbd', func_get_args());}
function label()      {return call_user_func_array('\Tiny\Tag::label', func_get_args());}
function legend()     {return call_user_func_array('\Tiny\Tag::legend', func_get_args());}
function li()         {return call_user_func_array('\Tiny\Tag::li', func_get_args());}
function link()       {return call_user_func_array('\Tiny\Tag::link', func_get_args());}
function main()       {return call_user_func_array('\Tiny\Tag::main', func_get_args());}
function map()        {return call_user_func_array('\Tiny\Tag::map', func_get_args());}
function mark()       {return call_user_func_array('\Tiny\Tag::mark', func_get_args());}
function menu()       {return call_user_func_array('\Tiny\Tag::menu', func_get_args());}
function meta()       {return call_user_func_array('\Tiny\Tag::meta', func_get_args());}
function meter()      {return call_user_func_array('\Tiny\Tag::meter', func_get_args());}
function nav()        {return call_user_func_array('\Tiny\Tag::nav', func_get_args());}
function noscript()   {return call_user_func_array('\Tiny\Tag::noscript', func_get_args());}
function object()     {return call_user_func_array('\Tiny\Tag::object', func_get_args());}
function ol()         {return call_user_func_array('\Tiny\Tag::ol', func_get_args());}
function optgroup()   {return call_user_func_array('\Tiny\Tag::optgroup', func_get_args());}
function option()     {return call_user_func_array('\Tiny\Tag::option', func_get_args());}
function output()     {return call_user_func_array('\Tiny\Tag::output', func_get_args());}
function p()          {return call_user_func_array('\Tiny\Tag::p', func_get_args());}
function picture()    {return call_user_func_array('\Tiny\Tag::picture', func_get_args());}
function pre()        {return call_user_func_array('\Tiny\Tag::pre', func_get_args());}
function progress()   {return call_user_func_array('\Tiny\Tag::progress', func_get_args());}
function q()          {return call_user_func_array('\Tiny\Tag::q', func_get_args());}
function rp()         {return call_user_func_array('\Tiny\Tag::rp', func_get_args());}
function rt()         {return call_user_func_array('\Tiny\Tag::rt', func_get_args());}
function ruby()       {return call_user_func_array('\Tiny\Tag::ruby', func_get_args());}
function s()          {return call_user_func_array('\Tiny\Tag::s', func_get_args());}
function samp()       {return call_user_func_array('\Tiny\Tag::samp', func_get_args());}
function script()     {return call_user_func_array('\Tiny\Tag::script', func_get_args());}
function section()    {return call_user_func_array('\Tiny\Tag::section', func_get_args());}
function select()     {return call_user_func_array('\Tiny\Tag::select', func_get_args());}
function slot()       {return call_user_func_array('\Tiny\Tag::slot', func_get_args());}
function small()      {return call_user_func_array('\Tiny\Tag::small', func_get_args());}
function source()     {return call_user_func_array('\Tiny\Tag::source', func_get_args());}
function span()       {return call_user_func_array('\Tiny\Tag::span', func_get_args());}
function strong()     {return call_user_func_array('\Tiny\Tag::strong', func_get_args());}
function style()      {return call_user_func_array('\Tiny\Tag::style', func_get_args());}
function sub()        {return call_user_func_array('\Tiny\Tag::sub', func_get_args());}
function summary()    {return call_user_func_array('\Tiny\Tag::summary', func_get_args());}
function sup()        {return call_user_func_array('\Tiny\Tag::sup', func_get_args());}
function table()      {return call_user_func_array('\Tiny\Tag::table', func_get_args());}
function tbody()      {return call_user_func_array('\Tiny\Tag::tbody', func_get_args());}
function td()         {return call_user_func_array('\Tiny\Tag::td', func_get_args());}
function template()   {return call_user_func_array('\Tiny\Tag::template', func_get_args());}
function textarea()   {return call_user_func_array('\Tiny\Tag::textarea', func_get_args());}
function tfoot()      {return call_user_func_array('\Tiny\Tag::tfoot', func_get_args());}
function th()         {return call_user_func_array('\Tiny\Tag::th', func_get_args());}
function thead()      {return call_user_func_array('\Tiny\Tag::thead', func_get_args());}
function time()       {return call_user_func_array('\Tiny\Tag::time', func_get_args());}
function title()      {return call_user_func_array('\Tiny\Tag::title', func_get_args());}
function tr()         {return call_user_func_array('\Tiny\Tag::tr', func_get_args());}
function track()      {return call_user_func_array('\Tiny\Tag::track', func_get_args());}
function u()          {return call_user_func_array('\Tiny\Tag::u', func_get_args());}
function ul()         {return call_user_func_array('\Tiny\Tag::ul', func_get_args());}
function video()      {return call_user_func_array('\Tiny\Tag::video', func_get_args());}
function wbr()        {return call_user_func_array('\Tiny\Tag::wbr', func_get_args());}
