<?php
namespace Tiny;

require_once __DIR__ . '/Htm.php';

function a()          {return call_user_func_array('\Tiny\Htm::a', func_get_args());}
function abbr()       {return call_user_func_array('\Tiny\Htm::abbr', func_get_args());}
function address()    {return call_user_func_array('\Tiny\Htm::address', func_get_args());}
function area()       {return call_user_func_array('\Tiny\Htm::area', func_get_args());}
function article()    {return call_user_func_array('\Tiny\Htm::article', func_get_args());}
function aside()      {return call_user_func_array('\Tiny\Htm::aside', func_get_args());}
function audio()      {return call_user_func_array('\Tiny\Htm::audio', func_get_args());}
function b()          {return call_user_func_array('\Tiny\Htm::b', func_get_args());}
function base()       {return call_user_func_array('\Tiny\Htm::base', func_get_args());}
function bdi()        {return call_user_func_array('\Tiny\Htm::bdi', func_get_args());}
function bdo()        {return call_user_func_array('\Tiny\Htm::bdo', func_get_args());}
function blockquote() {return call_user_func_array('\Tiny\Htm::blockquote', func_get_args());}
function body()       {return call_user_func_array('\Tiny\Htm::body', func_get_args());}
function br()         {return call_user_func_array('\Tiny\Htm::br', func_get_args());}
function button()     {return call_user_func_array('\Tiny\Htm::button', func_get_args());}
function canvas()     {return call_user_func_array('\Tiny\Htm::canvas', func_get_args());}
function caption()    {return call_user_func_array('\Tiny\Htm::caption', func_get_args());}
function cite()       {return call_user_func_array('\Tiny\Htm::cite', func_get_args());}
function code()       {return call_user_func_array('\Tiny\Htm::code', func_get_args());}
function col()        {return call_user_func_array('\Tiny\Htm::col', func_get_args());}
function colgroup()   {return call_user_func_array('\Tiny\Htm::colgroup', func_get_args());}
function data()       {return call_user_func_array('\Tiny\Htm::data', func_get_args());}
function datalist()   {return call_user_func_array('\Tiny\Htm::datalist', func_get_args());}
function dd()         {return call_user_func_array('\Tiny\Htm::dd', func_get_args());}
function del()        {return call_user_func_array('\Tiny\Htm::del', func_get_args());}
function details()    {return call_user_func_array('\Tiny\Htm::details', func_get_args());}
function dfn()        {return call_user_func_array('\Tiny\Htm::dfn', func_get_args());}
function dialog()     {return call_user_func_array('\Tiny\Htm::dialog', func_get_args());}
function div()        {return call_user_func_array('\Tiny\Htm::div', func_get_args());}
function dl()         {return call_user_func_array('\Tiny\Htm::dl', func_get_args());}
function dt()         {return call_user_func_array('\Tiny\Htm::dt', func_get_args());}
function em()         {return call_user_func_array('\Tiny\Htm::em', func_get_args());}
function embed()      {return call_user_func_array('\Tiny\Htm::embed', func_get_args());}
function fieldset()   {return call_user_func_array('\Tiny\Htm::fieldset', func_get_args());}
function figcaption() {return call_user_func_array('\Tiny\Htm::figcaption', func_get_args());}
function figure()     {return call_user_func_array('\Tiny\Htm::figure', func_get_args());}
function footer()     {return call_user_func_array('\Tiny\Htm::footer', func_get_args());}
function form()       {return call_user_func_array('\Tiny\Htm::form', func_get_args());}
function h1()         {return call_user_func_array('\Tiny\Htm::h1', func_get_args());}
function h2()         {return call_user_func_array('\Tiny\Htm::h2', func_get_args());}
function h3()         {return call_user_func_array('\Tiny\Htm::h3', func_get_args());}
function h4()         {return call_user_func_array('\Tiny\Htm::h4', func_get_args());}
function h5()         {return call_user_func_array('\Tiny\Htm::h5', func_get_args());}
function h6()         {return call_user_func_array('\Tiny\Htm::h6', func_get_args());}
function head()       {return call_user_func_array('\Tiny\Htm::head', func_get_args());}
function header()     {return call_user_func_array('\Tiny\Htm::header', func_get_args());}
function hgroup()     {return call_user_func_array('\Tiny\Htm::hgroup', func_get_args());}
function hr()         {return call_user_func_array('\Tiny\Htm::hr', func_get_args());}
function html()       {return call_user_func_array('\Tiny\Htm::html', func_get_args());}
function i()          {return call_user_func_array('\Tiny\Htm::i', func_get_args());}
function iframe()     {return call_user_func_array('\Tiny\Htm::iframe', func_get_args());}
function img()        {return call_user_func_array('\Tiny\Htm::img', func_get_args());}
function input()      {return call_user_func_array('\Tiny\Htm::input', func_get_args());}
function ins()        {return call_user_func_array('\Tiny\Htm::ins', func_get_args());}
function kbd()        {return call_user_func_array('\Tiny\Htm::kbd', func_get_args());}
function label()      {return call_user_func_array('\Tiny\Htm::label', func_get_args());}
function legend()     {return call_user_func_array('\Tiny\Htm::legend', func_get_args());}
function li()         {return call_user_func_array('\Tiny\Htm::li', func_get_args());}
function link()       {return call_user_func_array('\Tiny\Htm::link', func_get_args());}
function main()       {return call_user_func_array('\Tiny\Htm::main', func_get_args());}
function map()        {return call_user_func_array('\Tiny\Htm::map', func_get_args());}
function mark()       {return call_user_func_array('\Tiny\Htm::mark', func_get_args());}
function menu()       {return call_user_func_array('\Tiny\Htm::menu', func_get_args());}
function meta()       {return call_user_func_array('\Tiny\Htm::meta', func_get_args());}
function meter()      {return call_user_func_array('\Tiny\Htm::meter', func_get_args());}
function nav()        {return call_user_func_array('\Tiny\Htm::nav', func_get_args());}
function noscript()   {return call_user_func_array('\Tiny\Htm::noscript', func_get_args());}
function object()     {return call_user_func_array('\Tiny\Htm::object', func_get_args());}
function ol()         {return call_user_func_array('\Tiny\Htm::ol', func_get_args());}
function optgroup()   {return call_user_func_array('\Tiny\Htm::optgroup', func_get_args());}
function option()     {return call_user_func_array('\Tiny\Htm::option', func_get_args());}
function output()     {return call_user_func_array('\Tiny\Htm::output', func_get_args());}
function p()          {return call_user_func_array('\Tiny\Htm::p', func_get_args());}
function picture()    {return call_user_func_array('\Tiny\Htm::picture', func_get_args());}
function pre()        {return call_user_func_array('\Tiny\Htm::pre', func_get_args());}
function progress()   {return call_user_func_array('\Tiny\Htm::progress', func_get_args());}
function q()          {return call_user_func_array('\Tiny\Htm::q', func_get_args());}
function rp()         {return call_user_func_array('\Tiny\Htm::rp', func_get_args());}
function rt()         {return call_user_func_array('\Tiny\Htm::rt', func_get_args());}
function ruby()       {return call_user_func_array('\Tiny\Htm::ruby', func_get_args());}
function s()          {return call_user_func_array('\Tiny\Htm::s', func_get_args());}
function samp()       {return call_user_func_array('\Tiny\Htm::samp', func_get_args());}
function script()     {return call_user_func_array('\Tiny\Htm::script', func_get_args());}
function section()    {return call_user_func_array('\Tiny\Htm::section', func_get_args());}
function select()     {return call_user_func_array('\Tiny\Htm::select', func_get_args());}
function slot()       {return call_user_func_array('\Tiny\Htm::slot', func_get_args());}
function small()      {return call_user_func_array('\Tiny\Htm::small', func_get_args());}
function source()     {return call_user_func_array('\Tiny\Htm::source', func_get_args());}
function span()       {return call_user_func_array('\Tiny\Htm::span', func_get_args());}
function strong()     {return call_user_func_array('\Tiny\Htm::strong', func_get_args());}
function style()      {return call_user_func_array('\Tiny\Htm::style', func_get_args());}
function sub()        {return call_user_func_array('\Tiny\Htm::sub', func_get_args());}
function summary()    {return call_user_func_array('\Tiny\Htm::summary', func_get_args());}
function sup()        {return call_user_func_array('\Tiny\Htm::sup', func_get_args());}
function table()      {return call_user_func_array('\Tiny\Htm::table', func_get_args());}
function tbody()      {return call_user_func_array('\Tiny\Htm::tbody', func_get_args());}
function td()         {return call_user_func_array('\Tiny\Htm::td', func_get_args());}
function template()   {return call_user_func_array('\Tiny\Htm::template', func_get_args());}
function textarea()   {return call_user_func_array('\Tiny\Htm::textarea', func_get_args());}
function tfoot()      {return call_user_func_array('\Tiny\Htm::tfoot', func_get_args());}
function th()         {return call_user_func_array('\Tiny\Htm::th', func_get_args());}
function thead()      {return call_user_func_array('\Tiny\Htm::thead', func_get_args());}
function time()       {return call_user_func_array('\Tiny\Htm::time', func_get_args());}
function title()      {return call_user_func_array('\Tiny\Htm::title', func_get_args());}
function tr()         {return call_user_func_array('\Tiny\Htm::tr', func_get_args());}
function track()      {return call_user_func_array('\Tiny\Htm::track', func_get_args());}
function u()          {return call_user_func_array('\Tiny\Htm::u', func_get_args());}
function ul()         {return call_user_func_array('\Tiny\Htm::ul', func_get_args());}
function video()      {return call_user_func_array('\Tiny\Htm::video', func_get_args());}
function wbr()        {return call_user_func_array('\Tiny\Htm::wbr', func_get_args());}
