<?php declare(strict_types=1);
namespace Tiny;

function a(): Tag          {return call_user_func_array('\Tiny\Tag::a', func_get_args());}
function abbr(): Tag       {return call_user_func_array('\Tiny\Tag::abbr', func_get_args());}
function address(): Tag    {return call_user_func_array('\Tiny\Tag::address', func_get_args());}
function area(): Tag       {return call_user_func_array('\Tiny\Tag::area', func_get_args());}
function article(): Tag    {return call_user_func_array('\Tiny\Tag::article', func_get_args());}
function aside(): Tag      {return call_user_func_array('\Tiny\Tag::aside', func_get_args());}
function audio(): Tag      {return call_user_func_array('\Tiny\Tag::audio', func_get_args());}
function b(): Tag          {return call_user_func_array('\Tiny\Tag::b', func_get_args());}
function base(): Tag       {return call_user_func_array('\Tiny\Tag::base', func_get_args());}
function bdi(): Tag        {return call_user_func_array('\Tiny\Tag::bdi', func_get_args());}
function bdo(): Tag        {return call_user_func_array('\Tiny\Tag::bdo', func_get_args());}
function blockquote(): Tag {return call_user_func_array('\Tiny\Tag::blockquote', func_get_args());}
function body(): Tag       {return call_user_func_array('\Tiny\Tag::body', func_get_args());}
function br(): Tag         {return call_user_func_array('\Tiny\Tag::br', func_get_args());}
function button(): Tag     {return call_user_func_array('\Tiny\Tag::button', func_get_args());}
function canvas(): Tag     {return call_user_func_array('\Tiny\Tag::canvas', func_get_args());}
function caption(): Tag    {return call_user_func_array('\Tiny\Tag::caption', func_get_args());}
function cite(): Tag       {return call_user_func_array('\Tiny\Tag::cite', func_get_args());}
function code(): Tag       {return call_user_func_array('\Tiny\Tag::code', func_get_args());}
function col(): Tag        {return call_user_func_array('\Tiny\Tag::col', func_get_args());}
function colgroup(): Tag   {return call_user_func_array('\Tiny\Tag::colgroup', func_get_args());}
function data(): Tag       {return call_user_func_array('\Tiny\Tag::data', func_get_args());}
function datalist(): Tag   {return call_user_func_array('\Tiny\Tag::datalist', func_get_args());}
function dd(): Tag         {return call_user_func_array('\Tiny\Tag::dd', func_get_args());}
function del(): Tag        {return call_user_func_array('\Tiny\Tag::del', func_get_args());}
function details(): Tag    {return call_user_func_array('\Tiny\Tag::details', func_get_args());}
function dfn(): Tag        {return call_user_func_array('\Tiny\Tag::dfn', func_get_args());}
function dialog(): Tag     {return call_user_func_array('\Tiny\Tag::dialog', func_get_args());}
function div(): Tag        {return call_user_func_array('\Tiny\Tag::div', func_get_args());}
function dl(): Tag         {return call_user_func_array('\Tiny\Tag::dl', func_get_args());}
function dt(): Tag         {return call_user_func_array('\Tiny\Tag::dt', func_get_args());}
function em(): Tag         {return call_user_func_array('\Tiny\Tag::em', func_get_args());}
function embed(): Tag      {return call_user_func_array('\Tiny\Tag::embed', func_get_args());}
function fieldset(): Tag   {return call_user_func_array('\Tiny\Tag::fieldset', func_get_args());}
function figcaption(): Tag {return call_user_func_array('\Tiny\Tag::figcaption', func_get_args());}
function figure(): Tag     {return call_user_func_array('\Tiny\Tag::figure', func_get_args());}
function footer(): Tag     {return call_user_func_array('\Tiny\Tag::footer', func_get_args());}
function form(): Tag       {return call_user_func_array('\Tiny\Tag::form', func_get_args());}
function h1(): Tag         {return call_user_func_array('\Tiny\Tag::h1', func_get_args());}
function h2(): Tag         {return call_user_func_array('\Tiny\Tag::h2', func_get_args());}
function h3(): Tag         {return call_user_func_array('\Tiny\Tag::h3', func_get_args());}
function h4(): Tag         {return call_user_func_array('\Tiny\Tag::h4', func_get_args());}
function h5(): Tag         {return call_user_func_array('\Tiny\Tag::h5', func_get_args());}
function h6(): Tag         {return call_user_func_array('\Tiny\Tag::h6', func_get_args());}
function head(): Tag       {return call_user_func_array('\Tiny\Tag::head', func_get_args());}
function header(): Tag     {return call_user_func_array('\Tiny\Tag::header', func_get_args());}
function hgroup(): Tag     {return call_user_func_array('\Tiny\Tag::hgroup', func_get_args());}
function hr(): Tag         {return call_user_func_array('\Tiny\Tag::hr', func_get_args());}
function html(): Tag       {return call_user_func_array('\Tiny\Tag::html', func_get_args());}
function i(): Tag          {return call_user_func_array('\Tiny\Tag::i', func_get_args());}
function iframe(): Tag     {return call_user_func_array('\Tiny\Tag::iframe', func_get_args());}
function img(): Tag        {return call_user_func_array('\Tiny\Tag::img', func_get_args());}
function input(): Tag      {return call_user_func_array('\Tiny\Tag::input', func_get_args());}
function ins(): Tag        {return call_user_func_array('\Tiny\Tag::ins', func_get_args());}
function kbd(): Tag        {return call_user_func_array('\Tiny\Tag::kbd', func_get_args());}
function label(): Tag      {return call_user_func_array('\Tiny\Tag::label', func_get_args());}
function legend(): Tag     {return call_user_func_array('\Tiny\Tag::legend', func_get_args());}
function li(): Tag         {return call_user_func_array('\Tiny\Tag::li', func_get_args());}
function link(): Tag       {return call_user_func_array('\Tiny\Tag::link', func_get_args());}
function main(): Tag       {return call_user_func_array('\Tiny\Tag::main', func_get_args());}
function map(): Tag        {return call_user_func_array('\Tiny\Tag::map', func_get_args());}
function mark(): Tag       {return call_user_func_array('\Tiny\Tag::mark', func_get_args());}
function menu(): Tag       {return call_user_func_array('\Tiny\Tag::menu', func_get_args());}
function meta(): Tag       {return call_user_func_array('\Tiny\Tag::meta', func_get_args());}
function meter(): Tag      {return call_user_func_array('\Tiny\Tag::meter', func_get_args());}
function nav(): Tag        {return call_user_func_array('\Tiny\Tag::nav', func_get_args());}
function noscript(): Tag   {return call_user_func_array('\Tiny\Tag::noscript', func_get_args());}
function object(): Tag     {return call_user_func_array('\Tiny\Tag::object', func_get_args());}
function ol(): Tag         {return call_user_func_array('\Tiny\Tag::ol', func_get_args());}
function optgroup(): Tag   {return call_user_func_array('\Tiny\Tag::optgroup', func_get_args());}
function option(): Tag     {return call_user_func_array('\Tiny\Tag::option', func_get_args());}
function output(): Tag     {return call_user_func_array('\Tiny\Tag::output', func_get_args());}
function p(): Tag          {return call_user_func_array('\Tiny\Tag::p', func_get_args());}
function picture(): Tag    {return call_user_func_array('\Tiny\Tag::picture', func_get_args());}
function pre(): Tag        {return call_user_func_array('\Tiny\Tag::pre', func_get_args());}
function progress(): Tag   {return call_user_func_array('\Tiny\Tag::progress', func_get_args());}
function q(): Tag          {return call_user_func_array('\Tiny\Tag::q', func_get_args());}
function rp(): Tag         {return call_user_func_array('\Tiny\Tag::rp', func_get_args());}
function rt(): Tag         {return call_user_func_array('\Tiny\Tag::rt', func_get_args());}
function ruby(): Tag       {return call_user_func_array('\Tiny\Tag::ruby', func_get_args());}
function s(): Tag          {return call_user_func_array('\Tiny\Tag::s', func_get_args());}
function samp(): Tag       {return call_user_func_array('\Tiny\Tag::samp', func_get_args());}
function script(): Tag     {return call_user_func_array('\Tiny\Tag::script', func_get_args());}
function section(): Tag    {return call_user_func_array('\Tiny\Tag::section', func_get_args());}
function select(): Tag     {return call_user_func_array('\Tiny\Tag::select', func_get_args());}
function slot(): Tag       {return call_user_func_array('\Tiny\Tag::slot', func_get_args());}
function small(): Tag      {return call_user_func_array('\Tiny\Tag::small', func_get_args());}
function source(): Tag     {return call_user_func_array('\Tiny\Tag::source', func_get_args());}
function span(): Tag       {return call_user_func_array('\Tiny\Tag::span', func_get_args());}
function strong(): Tag     {return call_user_func_array('\Tiny\Tag::strong', func_get_args());}
function style(): Tag      {return call_user_func_array('\Tiny\Tag::style', func_get_args());}
function sub(): Tag        {return call_user_func_array('\Tiny\Tag::sub', func_get_args());}
function summary(): Tag    {return call_user_func_array('\Tiny\Tag::summary', func_get_args());}
function sup(): Tag        {return call_user_func_array('\Tiny\Tag::sup', func_get_args());}
function table(): Tag      {return call_user_func_array('\Tiny\Tag::table', func_get_args());}
function tbody(): Tag      {return call_user_func_array('\Tiny\Tag::tbody', func_get_args());}
function td(): Tag         {return call_user_func_array('\Tiny\Tag::td', func_get_args());}
function template(): Tag   {return call_user_func_array('\Tiny\Tag::template', func_get_args());}
function textarea(): Tag   {return call_user_func_array('\Tiny\Tag::textarea', func_get_args());}
function tfoot(): Tag      {return call_user_func_array('\Tiny\Tag::tfoot', func_get_args());}
function th(): Tag         {return call_user_func_array('\Tiny\Tag::th', func_get_args());}
function thead(): Tag      {return call_user_func_array('\Tiny\Tag::thead', func_get_args());}
function time(): Tag       {return call_user_func_array('\Tiny\Tag::time', func_get_args());}
function title(): Tag      {return call_user_func_array('\Tiny\Tag::title', func_get_args());}
function tr(): Tag         {return call_user_func_array('\Tiny\Tag::tr', func_get_args());}
function track(): Tag      {return call_user_func_array('\Tiny\Tag::track', func_get_args());}
function u(): Tag          {return call_user_func_array('\Tiny\Tag::u', func_get_args());}
function ul(): Tag         {return call_user_func_array('\Tiny\Tag::ul', func_get_args());}
function video(): Tag      {return call_user_func_array('\Tiny\Tag::video', func_get_args());}
function wbr(): Tag        {return call_user_func_array('\Tiny\Tag::wbr', func_get_args());}
